services:
  wp:
    image: docker.io/wordpress:latest
    volumes:
      - wp_data:/var/www/html
    restart: unless-stopped
    networks:
      - master
      - wordpress
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db

  db:
    image: docker.io/yobasystems/alpine-mariadb
    volumes:
      - db_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    networks:
      - wordpress
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${DB_PASSWORD}

volumes:
  db_data:
    driver: local
  wp_data:
    driver: local

networks:
  master:
    name: master
    external: true
  wordpress:
