services:
  wp:
    image: docker.io/wordpress:latest
    volumes:
      - wp_data:/var/www/html
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.${STACK}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${STACK}.entrypoints=https
      - traefik.http.routers.${STACK}.tls.certresolver=letsencrypt
      - traefik.http.services.${STACK}.loadbalancer.server.port=80
    networks:
      - traefik
      - wordpress
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db

  db:
    image: docker.io/yobasystems/alpine-mariadb
    volumes:
      - db_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    networks:
      - wordpress
    expose:
      - 3306
    labels:
      - traefik.enable=false
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${DB_PASSWORD}

volumes:
  db_data:
    driver: local
  wp_data:
    driver: local

networks:
  traefik:
    name: traefik
  wordpress:
