version: '3.8'

services:
  adguard:
    image: docker.io/adguard/adguardhome
    restart: unless-stopped
    privileged: true
    ports:
      - '53:53'
      - '53:53/udp'
      - '3000:3000'
    environment:
      TZ: Europe/Berlin
