services:
  adguard:
    container_name: adguard
    image: docker.io/adguard/adguardhome
    restart: unless-stopped
    ports:
      - 53:53
      - 53:53/udp
    volumes:
      - work:/opt/adguardhome/work
      - conf:/opt/adguardhome/conf
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.adguard.rule=Host(${DOMAIN})
      - traefik.http.routers.adguard.entrypoints=http
      - traefik.http.services.adguard.loadbalancer.server.port=3000
    environment:
      TZ: Europe/Berlin

volumes:
  work:
    driver: local
  conf:
    driver: local

networks:
  traefik:
    name: traefik