services:
  app:
    container_name: proxy
    image: docker.io/jc21/nginx-proxy-manager:2.10.2
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
    networks:
      - master

networks:
  master:
    name: master
    external: true
