services:
  nginx:
    image: docker.io/nginx
    restart: unless-stopped
    volumes:
      - nginx_data:/usr/share/nginx/html
    networks:
      - master
    environment:
      - TZ=Europe/Berlin
      - NGINX_PORT=80

networks:
  master:
    name: master
    external: true

volumes:
  nginx_data:
    driver: local
