services:
  nginx:
    image: docker.io/nginx
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.${INSTANCE_NAME}.rule=Host(${DOMAIN})
      - traefik.http.routers.${INSTANCE_NAME}.entrypoints=http
      - traefik.http.services.${INSTANCE_NAME}.loadbalancer.server.port=80
    environment:
      - TZ=Europe/Berlin
      - NGINX_HOST=${DOMAIN}
      - NGINX_PORT=80

networks:
  traefik:
    name: traefik