services:
  cloudflare-ddns:
    container_name: cloudflare-ddns
    image: docker.io/oznu/cloudflare-ddns
    restart: unless-stopped
    environment:
      - API_KEY=${API_KEY}
      - ZONE=${DOMAIN}
      - SUBDOMAIN=${SUBDOMAIN}
      - PROXIED=true
      - TZ=Europe/Berlin
