version: '3.8'

services:
  traefik:
    image: docker.io/traefik
    privileged: true
    restart: unless-stopped
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /run/podman/podman.sock:/var/run/docker.sock:Z
    environment:
      TZ: Europe/Berlin
