services:
  traefik:
    container_name: traefik
    image: docker.io/traefik
    restart: unless-stopped
    privileged: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:Z
      - letsencrypt:/letsencrypt
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(${DOMAIN})
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.services.traefik.loadbalancer.server.port=8080
    environment:
      - TZ=Europe/Berlin
    command:
      - --log.level=DEBUG
      - --providers.docker=true
      - --api.dashboard=true
      - --api.insecure=true
      # - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      # - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      # - --certificatesresolvers.letsencrypt.acme.email=$ACME_EMAIL
      # - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --entrypoints.http.address=:80
      # - --entrypoints.http.http.redirections.entrypoint.to=https
      # - --entrypoints.http.http.redirections.entrypoint.scheme=https
      - --entrypoints.https.address=:443
      - --entrypoints.https.http.tls=true
      - --entrypoints.https.http.tls.certResolver=letsencrypt
      # - --entrypoints.https.http.tls.domains[0].main=${DOMAIN}
      # - --entrypoints.https.http.tls.domains[0].sans=*.${DOMAIN}

volumes:
  letsencrypt:
    driver: local

networks:
  traefik:
    name: traefik
