services:
  portainer:
    container_name: portainer
    image: docker.io/portainer/portainer-ce
    restart: always
    privileged: true
    ports:
      - 9443:9443
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock:Z
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.sylvanas.local`)
      - traefik.http.routers.portainer.entrypoints=https
      - traefik.http.routers.portainer.tls.certresolver=letsencrypt
      - traefik.http.services.portainer.loadbalancer.server.port=9443

volumes:
  data:
    driver: local
    
networks:
  traefik:
    external: true
